# Generated by Django 2.1.4 on 2019-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_players', models.IntegerField()),
                ('result', models.CharField(blank=True, max_length=300, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
